[package]
name = "flo-event"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2.22", features = ["sync"] }
tracing = "0.1"
futures = "0.3.5"
