# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    curl https://sh.rustup.rs/ -sSf | sh -s -- --default-toolchain stable -y
  displayName: 'install rust'
 
- script: |
    cargo build -p flo-controller-service --release
  displayName: 'build flo controller'

- script: |
    mv ./target/release ./build
  displayName: 'move files for docker'

- task: Docker@2
  inputs:
    containerRegistry: 'Fluxxu Docker Hub'
    repository: 'fluxxu/flo-controller'
    command: 'buildAndPush'
    Dockerfile: './build/controller.Dockerfile'
    buildContext: "."
    tags: |
      $(Build.BuildID)
      latest