[workspace]
members = [
  "./crates/codegen",
  "./crates/util",
  "./crates/w3gs",
  "./crates/w3map",
  "./crates/blp",
  "./crates/lobby",
  "./crates/lan"
]

[patch.crates-io]
stormlib = { path = "../stormlib-rs/crates/stormlib" }
stormlib-sys = { path = "../stormlib-rs/crates/stormlib-sys" }
trust-dns-proto = { git = "https://github.com/fluxxu/trust-dns.git", branch = "main" }
trust-dns-client = { git = "https://github.com/fluxxu/trust-dns.git", branch = "main" }