[workspace]
members = [
  "./crates/codegen",
  "./crates/platform",
  "./crates/util",
  "./crates/w3gs",
  "./crates/w3map",
  "./crates/blp",
  "./crates/lobby",
  "./crates/lan",
  "./crates/w3client",
  "./crates/log",
  "./crates/config",
  "./crates/net",
  "./crates/w3storage",
  "./crates/w3replay",
  "./crates/node",

  "./binaries/flo-lobby-service",
  "./binaries/flo-connect",
  "./binaries/flo-map-checksum-dump",
]

[patch.crates-io]
stormlib = { path = "../stormlib-rs/crates/stormlib" }
stormlib-sys = { path = "../stormlib-rs/crates/stormlib-sys" }
trust-dns-proto = { git = "https://github.com/fluxxu/trust-dns.git", branch = "main" }
trust-dns-client = { git = "https://github.com/fluxxu/trust-dns.git", branch = "main" }
casclib = { git = "https://github.com/wc3tools/casclib-rs.git" }
casclib-sys = { git = "https://github.com/wc3tools/casclib-rs.git" }
flo-grpc = { path = "../flo-grpc" }