[package]
name = "flo-w3c"
version = "0.0.1"
authors = ["Qeenon <codemasha@gmail.com>"]
edition = "2018"

[dependencies]
ureq = { version = "2", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
once_cell = "1.5"
