[package]
name = "flo-platform"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
flo-config = { path = "../config" }
thiserror = "1"
dotenv = "0.15"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["processthreadsapi", "shlobj", "knownfolders", "winerror", "combaseapi"] }
widestring = "0.4"

[target.'cfg(target_os = "macos")'.dependencies]
plist = "1.3"
home-dir = "0.1"

[build-dependencies]
cc = "1.0"
