[package]
name = "flo-util"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
flo-codegen = { path = "../codegen" }

thiserror = "1"
tokio-util = { version = "0.6", features = ["codec"] }
bytes = "1.0"
pretty-hex = "0.2"
enumflags2 = "0.6"
lazy_static = "1"
impl-trait-for-tuples = "0.2"
