[package]
name = "flo-w3storage"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
flo-platform = { path = "../platform" }
casclib = "0.2"
thiserror = "1.0"
parking_lot = "0.11"
glob = "0.3"
bytes = "1.2.1"
serde = { version = "1", features = ["derive"] }
walkdir = "2"

[dev-dependencies]
dotenv = "0.15"
