[package]
name = "flo-w3storage"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
flo-platform = { path = "../platform" }
casclib = "0.2.1"
thiserror = "1.0.20"
parking_lot = "0.11.0"
glob = "0.3.0"
bytes = "0.5.5"

[dev-dependencies]
dotenv = "0.15.0"