[package]
name = "flo-w3gs"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
flo-util = { path = "../util" }

byteorder = "1"
bitflags = "1"
thiserror = "1"
lazy_static = "1"
prost = "0.6"
futures = "0.3"
tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.3.1", features = ["codec"] }
rand = "0.7.3"
crc32fast = "1.2.0"

[build-dependencies]
prost-build = { version = "0.6" }