[package]
name = "flo-node"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
flo-util = { path = "../util" }
flo-w3gs = { path = "../w3gs" }
flo-net = { path = "../net" }
flo-constants = { path = "../constants" }

thiserror = "1.0.20"
bytes = "0.5.6"
futures = "0.3.5"
tokio = { version = "0.2.22", features = ["time", "sync", "stream", "macros", "blocking"] }
tracing = "0.1"
tracing-futures = "0.2.4"
parking_lot = "0.11.0"
s2-grpc-utils = "0.2"
prometheus = "0.9.0"
lazy_static = "1.0"
uuid = { version = "0.8.1", features = ["v4"] }

[build-dependencies]
flo-constants = { path = "../constants" }