[package]
name = "flo-lobby"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
flo-util = { path = "../util" }
flo-w3gs = { path = "../w3gs" }
flo-w3map = { path = "../w3map"}
flo-w3storage = { path = "../w3storage"}