[package]
name = "flo-types"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flo-net = { path = "../net" }
flo-w3gs = { path = "../w3gs" }
flo-grpc = { path = "../../deps/flo-grpc" }

s2-grpc-utils = "0.2"
serde = { version = "1.0", features = ["derive"] }
