[package]
name = "flo-w3replay"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
flo-util = { path = "../util" }
flo-w3gs = { path = "../w3gs" }

flate2 = "1.0.16"
thiserror = "1"
bitflags = "1"
crc32fast = "1.2.0"
bytes = "0.5.5"
