[package]
name = "flo-w3replay"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
flo-util = { path = "../util" }
flo-w3gs = { path = "../w3gs" }

flate2 = { version = "1.0", features = ["zlib"], default-features = false }
thiserror = "1"
bitflags = "1"
bytes = "1.1.0"