[package]
name = "flo-observer"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
flo-net = { path = "../net" }
flo-w3gs = { path = "../w3gs" }
bytes = "1.0"
rusoto_core = "0.46.0"
rusoto_kinesis = "0.46.0"