[package]
name = "flo-w3map"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[features]
w3storage = [
  "flo-w3storage"
]

[dependencies]
flo-util = { path = "../util" }
flo-blp = { path = "../blp" }
flo-w3storage = { path = "../w3storage", optional = true }

stormlib = "0.1"
thiserror = "1"
bitflags = "1"
image = "0.23"
lazy_static = "1"
ceres-mpq = "0.1"
crc32fast = "1.3"
sha1 = "0.6"
