name: Rust

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.PAT_MY_TOKEN}}
        submodules: recursive
    - name: Check
      run: cargo check -p flo-lobby-service && cargo check -p flo-node-service
