on:
  push:
    branches:
      - "develop"

name: Release Docker

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: fluxxu
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push - flo-controller
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fluxxu/flo-controller:${{ github.sha }},fluxxu/flo-controller:latest
          file: './build/controller.Dockerfile'

      - name: Build and push - flo-node
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fluxxu/flo-node:${{ github.sha }},fluxxu/flo-node:latest
          file: './build/node.Dockerfile'

      - name: Build and push - flo-stats
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fluxxu/flo-stats:${{ github.sha }},fluxxu/flo-stats:latest
          file: './build/stats.Dockerfile'